name: Email ingest trigger

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  call-endpoint:
    runs-on: ubuntu-latest
    steps:
      - name: Call ingest endpoint
        run: |
          INGEST_ENDPOINT_URL="https://jobapplications-badhh8h5afdpcqe8.centralus-01.azurewebsites.net/run-ingest"
          curl --fail --show-error --silent "${INGEST_ENDPOINT_URL}"
